name: cupertino_list_tile_example
description: CupertinoListTile for Flutter example app.
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_list_tile:
    path: ../
  flutter:
    sdk: flutter
